Description of lookForFlux
lookForFlux
PURPOSE
Uday Tripathi 7/2016
SYNOPSIS
function score=lookForFlux(model,exchangeReaction,mets)
DESCRIPTION
 Uday Tripathi 7/2016
 Sample excRxn: 'EX Nitrite e0'
 Workflow: a=load(model) a=a.model lookForFlux(model,exchangeReaction)
CROSS-REFERENCE INFORMATION
This function calls:
changeMetLevels CHANGEMETLEVELS Set the uptake reaction rate to 0 for all metabolites in
This function is called by:
runTest Uday Tripathi 7/2016
scoreCobra Uday Tripathi 7/2016
SOURCE CODE
% Uday Tripathi 7/2016
% Sample excRxn: 'EX Nitrite e0'
% Workflow: a=load(model) a=a.model lookForFlux(model,exchangeReaction)
% Same as cobraFlux within Main class
function score=lookForFlux(model,exchangeReaction,mets)
    model=changeMetLevels(model,mets);
    score=0;
    indexOfRxn=strmatch(exchangeReaction,model.rxnNames);
    if (isempty(indexOfRxn)==0)
        temp=model.S(:,indexOfRxn);
        tempArr=nonzeros(temp);
        opt=optimizeCbModel(model,'max',0,true);
        flux=opt.x(indexOfRxn);
        for i=1:length(tempArr)
            score=score+tempArr(i); % adds up scores from Cobra optimized model
        end
        score=score*flux;
    else
        score=0;
    end
end