Description of testSerialDilution
testSerialDilution
PURPOSE
A script to test out the serial dilution functions
SYNOPSIS
This is a script file.
DESCRIPTION
A script to test out the serial dilution functions
CROSS-REFERENCE INFORMATION
This function calls:
setInitialPop SETINITIALPOP Automatically generates initial population placements for
createLayout CREATELAYOUT intialize a new blank Layout or one using the given models
runSerialDilution runSerialDilution(layout,nCycles,dilutionFactor,includeSpentMedia,directory)
media
This function is called by:
SOURCE CODE
%A script to test out the serial dilution functions
load('iJO1366.mat');
layout = createLayout();
layout = addModel(layout,iJO1366);
layout = addModel(layout,iJO1366);
layout.media_amt(1:length(layout.mets)) = 0.01;
layout = setInitialPop(layout,'1x1');
layout.initial_pop(2) = layout.initial_pop(2)*2;
[biomass,t,media] = runSerialDilution(layout,4,20,true,'C:\sync\biomes\scripts\tmp');