function createPackageParamsFile( directory, filename, params )
%CREATEPACKAGEPARAMSFILE Create the package params file for a COMETS run.
%Input:
%   directory: location of the output file
%   params: a CometsParams object

%field names and values should be case insensitive.

%names of possible fields
allparams = {'biomassLogFormat',...
    'biomassLogName',...
    'biomassLogRage',...
    'biomassMotionStyle',...
    'defaultAlpha',...
    'defaultDiffConst',...
    'defaultHill',...
    'defaultKm',...
    'defaultVmax',...
    'defaultW',...
    'exchangeStyle',...
    'flowDiffRate',...
    'fluxLogFormat',...
    'fluxLogName',...
    'fluxLogRate',...
    'growthDiffRate',...
    'manifestFileName',...
    'mediaLogFormat',...
    'mediaLogName',...
    'mediaLogRate',...
    'numDiffPerStep',...
    'numRunThreads',...
    'totalBiomassLogName',...
    'totalBiomassLogRate',...
    'useLogNameTimeStamp',...
    'writeBiomassLog',...
    'writeMediaLog',...
    'writeTotalBiomassLog'};

%ensure these are written as 'true' or 'false'
booleanparams = {'writeFluxLog','writeMediaLog','writeBiomassLog',...
    'writeTotalBiomassLog','useLogNameTimeStamp'};

f = fopen(fullfile(directory,filename),'w');

pfields = fields(params);
usedIdx = ismember(upper(pfields),upper(allparams));
used = pfields(usedIdx); %the names of fields which occur in the given CometsParams

    function printparam(name)
        val = params.(name);
        if ismember(upper(name),upper(booleanparams))
            if val
                fprintf(f,'%s = true \n',name);
            else
                fprintf(f,'%s = false \n',name);
            end
        elseif isnumeric(val)
            fprintf(f,'%s = %d \n',name,val);
        else
            fprintf(f,'%s = %s \n',name,val);
        end
    end

cellfun(@printparam,used);

fclose(f);

end

